name: Deploy Infrastructure To Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Enables manual trigger for terraform apply

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Deploy Infrastructure To Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        run: |
          echo "Setting AWS Credentials..."
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: stages/dev/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: stages/dev/

      - name: Terraform Validate
        run: terraform validate
        working-directory: stages/dev/

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: stages/dev/
        continue-on-error: false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: stages/dev/tfplan

      #TODO: Add manual approval for terraform apply
      #      - uses: trstringer/manual-approval@v1
      #        with:
      #          secret: ${{ github.TOKEN }}
      #          approvers: GITHUB Username
      #          minimum-approvals: 1
      #          issue-title: "Deploying to dev"
      #          issue-body: "Review the terraform plan, then approve or deny the deployment to dev."
      #          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop'
        run: terraform apply -auto-approve tfplan
        working-directory: stages/dev/
